# Site settings
title: Data Citation Community of Practice
email: sstall@agu.org, cerdmann@agu.org, caroline.m.coward@jpl.nasa.gov, daagarwal@lbl.gov
description: > # this means to ignore newlines until "baseurl:"
  Date
baseurl:  /DataCitationCoP
url:  https://agu-data.github.io
twitter_username: 
github_username:  AGU-Data

# Build settings
markdown: kramdown

highlighter: rouge

# Pagination
paginate: 15
paginate_path: "/blog/page:num/"

