# Site settings
title: Data Comms Workshop
email: cerdmann@agu.org
description: > # this means to ignore newlines until "baseurl:"
  Date
baseurl:  /datacomm
url:  https://agu-data.github.io
twitter_username: libcce
github_username:  libcce

# Build settings
markdown: kramdown

highlighter: rouge

# Pagination
paginate: 15
paginate_path: "/blog/page:num/"

