# Site settings
title: JupyterDay in the Triangle
email: chris@carpentries.org
description: > # this means to ignore newlines until "baseurl:"
  November 13, 2018 @ UNC Chapel Hill
baseurl:  /TriangleJupyter
url:  https://github.com/libcce
twitter_username: libcce
github_username:  libcce

# Build settings
markdown: kramdown

highlighter: rouge

# Pagination
paginate: 15
paginate_path: "/blog/page:num/"

