# Site settings
title: Jupyter in the Triangle
email: chris@carpentries.org
description: > # this means to ignore newlines until "baseurl:"
  A Jupyter Pop-Up Event
baseurl:  /TriangleJupyter/
url:  https://github.com/libcce
twitter_username: libcce
github_username:  libcce

# Build settings
markdown: kramdown

highlighter: rouge

# Pagination
paginate: 15
paginate_path: "/blog/page:num/"

